/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaminas;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author DAW2
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        setTitle("Buscaminas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbDificultad = new javax.swing.ButtonGroup();
        rdFacil = new javax.swing.JRadioButton();
        rdNormal = new javax.swing.JRadioButton();
        rdDificil = new javax.swing.JRadioButton();
        btnEmpezar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbDificultad.add(rdFacil);
        rdFacil.setText("Facil 8x8");
        rdFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFacilActionPerformed(evt);
            }
        });

        cmbDificultad.add(rdNormal);
        rdNormal.setText("Normal 16x16");
        rdNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNormalActionPerformed(evt);
            }
        });

        cmbDificultad.add(rdDificil);
        rdDificil.setText("Dificil 16x30");
        rdDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDificilActionPerformed(evt);
            }
        });

        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmpezar)
                    .addComponent(rdFacil)
                    .addComponent(rdNormal)
                    .addComponent(rdDificil))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(rdFacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdDificil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnEmpezar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int num;
    private void rdFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFacilActionPerformed
        // TODO add your handling code here:
        dificultad(1);
        //System.out.println(this.rdFacil.);
           /* Image img = new ImageIcon(this.getClass().getResource("../img/sss.jpg")).getImage();
            Image imagenescalada = img.getScaledInstance(this.lbl.getWidth(), this.lbl.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon icn=new ImageIcon(imagenescalada);
            this.lbl.setIcon(icn);*/
    }//GEN-LAST:event_rdFacilActionPerformed

    private void rdNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNormalActionPerformed
        // TODO add your handling code here:
        dificultad(2);
    }//GEN-LAST:event_rdNormalActionPerformed

    private void rdDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDificilActionPerformed
        // TODO add your handling code here:
        dificultad(3);
    }//GEN-LAST:event_rdDificilActionPerformed

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        // TODO add your handling code here:
        System.out.print("Empieza el juego, dificultad :");
        Ventana2 ventana=new Ventana2();
        switch(this.num){
            case 1:
                System.out.println("Facil");
                ventana.creargraella(8,8,10);
                break;
            case 2:
                System.out.println("Medio");
                ventana.creargraella(16,16,40);
                break;
            case 3:
                System.out.println("Dificil");
                ventana.creargraella(30,16,99);
                break;
            default:
                System.out.println("Error");
                break;
        }
        this.dispose();
    }//GEN-LAST:event_btnEmpezarActionPerformed
void dificultad(int num){
    System.out.println(num);
    this.num=num;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpezar;
    private javax.swing.ButtonGroup cmbDificultad;
    private javax.swing.JRadioButton rdDificil;
    private javax.swing.JRadioButton rdFacil;
    private javax.swing.JRadioButton rdNormal;
    // End of variables declaration//GEN-END:variables
}
